name: type-checking

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install checking requirements
        run: |
          pip install --upgrade pip
          pip install ruff mypy
      - name: ruff
        run: ruff check tests yogo --ignore E501 --ignore E722
      - name: mypy
        run: mypy --ignore-missing-imports yogo
